{% set name = "more-itertools" %}
{% set version = "4.1.0" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "c9ce7eccdcb901a2c75d326ea134e0886abfbea5f93e91cc95de9507c0816c44" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash }}

build:
  number: {{ build }}
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  build:
    - python
    - pip

  run:
    - python
    - six >=1.0.0,<2.0.0

test:
  imports:
    - more_itertools
    - more_itertools.tests

about:
  home: https://github.com/erikrose/more-itertools
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: 'More routines for operating on iterables, beyond itertools'
  dev_url: https://github.com/erikrose/more-itertools
  doc_url: https://more-itertools.readthedocs.io/en/latest/api.html

extra:
  recipe-maintainers:
    - pmlandwehr
