{% set name = "more-itertools" %}
{% set version = "10.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9fddd5403be01a94b204faadcff459ec3568cf110265d3c54323e1e866ad29d3

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - flit-core
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - more_itertools
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/more-itertools/more-itertools
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: More routines for operating on iterables, beyond itertools
  dev_url: https://github.com/more-itertools/more-itertools
  doc_url: https://more-itertools.readthedocs.io/en/latest/api.html

extra:
  recipe-maintainers:
    - dbast
