{% set name = "more-itertools" %}
{% set version = "6.0.0" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "590044e3942351a1bdb1de960b739ff4ce277960f2425ad4509446dbace8d9d1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - more_itertools
    - more_itertools.tests

about:
  home: https://github.com/erikrose/more-itertools
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: 'More routines for operating on iterables, beyond itertools'
  dev_url: https://github.com/erikrose/more-itertools
  doc_url: https://more-itertools.readthedocs.io/en/latest/api.html

extra:
  recipe-maintainers:
    - pmlandwehr
