{% set name = "more-itertools" %}
{% set version = "8.0.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: b84b238cce0d9adad5ed87e745778d20a3f8487d0f0cb8b8a586816c7496458d

build:
  number: 0
  noarch: "python"
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - python >=3.4

test:
  imports:
    - more_itertools

about:
  home: https://github.com/erikrose/more-itertools
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: 'More routines for operating on iterables, beyond itertools'
  dev_url: https://github.com/erikrose/more-itertools
  doc_url: https://more-itertools.readthedocs.io/en/latest/api.html

extra:
  recipe-maintainers:
    - pmlandwehr
    - dbast
