{% set name = "more-itertools" %}
{% set version = "10.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fe0e63c4ab068eac62410ab05cccca2dc71ec44ba8ef29916a0090df061cf923

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - flit-core
    - pip
    - python >=3.8
  run:
    - python >=3.8

test:
  imports:
    - more_itertools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/more-itertools/more-itertools
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: More routines for operating on iterables, beyond itertools
  dev_url: https://github.com/more-itertools/more-itertools
  doc_url: https://more-itertools.readthedocs.io/en/latest/api.html

extra:
  recipe-maintainers:
    - dbast
